## Core Deployment Settings
deployment:
  kong:
    enabled: true  # This fixes the nil pointer error for .Values.deployment.kong.enabled
  serviceAccount:
    create: true
    automountServiceAccountToken: false
  daemonset: false
  hostNetwork: false
  revisionHistoryLimit: 10
  prefixDir:
    sizeLimit: 256Mi
  tmpDir:
    sizeLimit: 1Gi

## Image Configuration
image:
  repository: kong/kong-gateway
  tag: "3.10"
  pullPolicy: IfNotPresent

## Dataplane Mode Settings
env:
  # Core Dataplane Settings
  role: data_plane
  database: "off"
  
  # Konnect Connection Settings
  cluster_mtls: pki
  cluster_control_plane: c897b00927.us.cp0.konghq.com:443
  cluster_server_name: c897b00927.us.cp0.konghq.com
  cluster_telemetry_endpoint: c897b00927.us.tp0.konghq.com:443
  cluster_telemetry_server_name: c897b00927.us.tp0.konghq.com
  konnect_mode: "on"
  
  # Certificate Configuration
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: system
  
  # Performance Tuning
  nginx_worker_processes: "1"
  router_flavor: expressions
  upstream_keepalive_max_requests: "100000"
  nginx_http_keepalive_requests: "100000"
  dns_stale_ttl: "3600"
  
  # Logging
  proxy_access_log: "off"
  vitals: "off"

## Service Configuration
proxy:
  enabled: true
  type: LoadBalancer
  loadBalancerClass: ""
  
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
    
  tls:
    enabled: true
    servicePort: 443
    containerPort: 8443
    parameters:
    - http2

# Explicitly disable UDP proxy to prevent template errors
udpProxy:
  enabled: false

## Disable Unnecessary Components
ingressController:
  enabled: false
  installCRDs: false

admin:
  enabled: false

## Resource Configuration
resources:
  requests:
    cpu: 1
    memory: "2Gi"
  limits:
    cpu: 2
    memory: "4Gi"

replicaCount: 2

## Security Configuration
securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
    - ALL

## Secrets Volume Mount
secretVolumes:
- kong-cluster-cert

## Disable Monitoring
serviceMonitor:
  enabled: false

## Enterprise Features (Disabled)
enterprise:
  enabled: false

## Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

## Update Strategy
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

## Migration Settings
migrations:
  preUpgrade: false  # Disabled for dataplane
  postUpgrade: false # Disabled for dataplane